### ISSUE TITLE
How to apply GCR to Google API?

### ISSUE THREAD

**Issue by fuminori-ido** [mastahyeti/gcr#7]
(My question is a how-to rather than issue report so that it may not be suitable to post here.  In that case, please let me know where I can post.  By the way, let me ask my question here.)

I would like to apply GCR to Google API like [analyze_sentiment](https://googleapis.dev/ruby/google-cloud-language/latest/Google/Cloud/Language/V1/LanguageServiceClient.html#analyze_sentiment-instance_method) 

I tried as follows:

```
GCR.cassette_dir = 'test/data/gcr'
gcl = Google::Cloud::Language.new(version: :v1, credentials: SOME_CREDENTIAL_INFO)
GCR.stub = gcl.language_service_stub
GCR.with_cassette('gcp') do
client = Google::Cloud::Language.new(version: :v1, credentials: SOME_CREDENTIAL_INFO)
response = client.analyze_sentiment(content: 'hello', type: :PLAIN_TEXT, language: :ja)
```
However, it failed as follows at the last line of code flagment above:

> Google::Gax::RetryError: GaxError Exception occurred in retry method that was not classified as transient, caused by undefined method `decode_json' for GRPC::ActiveCall::Operation:Class

'decode_json' looks coming from GCR, but I have no idea what happened...

Would you point out what is wrong on my code?

**Comment by btoews** [comment]
Hi. I have never used the `Google::Cloud::Language` library and have no idea if it would work with this gem. It looks like the library isn't using the GRPC library in a way that works with this gem, but I don't have any ideas for fixing this. Sorry.

**Comment by qnm** [comment]
@fuminori-ido Hi! Did you find a solution to using GCR with Google's API? I think I'm about to hit the same issue.

**Comment by NielsKSchjoedt** [comment]
+1
